name: Testim E2E
on: [push]

jobs:
    run-testimio-cli:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v4
              with:
                node-version: '22.14.0'
                # You can also change 'lts' to any supported LTS Node.js version.
            - run: npm install -g @testim/testim-cli
            - run: testim --token "1UirXpOB5K37HMxV3yK1f9iu0a5x26C2HA5E5jWNMJObLS6sE3" --project "9sSkgSujJmdD3xYQFFLl" --grid "testim-ha-grid" --mode "selenium" --branch "4Pines" --test-plan "Cross Browser 4Pines" --parallel 2
